# -*- coding: utf-8 -*-
"""assignment_2_B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XWVB3F4W_-lSnSZdOkrZSqzJv16q_0yG
"""

import numpy as np
import math

n = 1000000
f_sum = 0
f_sq_sum = 0

for i in range(n):
    x = np.random.uniform(low=0, high=1)
    y = 2*(math.exp(x)*x)

    f_sum += y
    f_sq_sum += y**2

f_avg = f_sum/n
f_sq_avg = f_sq_sum/n 


integral = f_avg * 1
error = 1 / math.sqrt(n) * math.sqrt(f_sq_avg-f_avg**2)
print(integral)
print(error)