# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kqXbvjT4lN84QgKLZSim-tG9eb3XrMiv
"""

import numpy as np
import matplotlib.pyplot as plt
import math
np.random.seed(0)

n=1000
hit=0
hit_x=[]
hit_y=[]

miss_x=[]
miss_y=[]    
total_area = 10
radius=3
for i in range(n):
  x=np.random.uniform(low=-5.0,high=5.0)
  y=np.random.uniform(low=-5.0,high=5.0)
  if math.sqrt(x**2+y**2) <= radius:
    hit+=1
    hit_x.append(y)
    hit_y.append(x)  
  
  else:
    miss_x.append(x)
    miss_y.append(y)
    
    
est_pi= (hit*total_area**2)/(n*radius**2)

print(hit)
print('estimated pi value :',est_pi)

plt.scatter(hit_x,hit_y,c='red')
plt.scatter(miss_x,miss_y,c='green')
plt.show()